name: Kubernetes deployment
on:
 push:
  branches:
    - main
jobs:
  deployment-Kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        
      - name: setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          
      - name: verify access
        run: kubectl get nodes
